#!/bin/bash

if [[ -z "${SERVICE_NAME}" ]]; then
  exec rethinkdb --bind all $@
else
  MIN_NODES_SIZE="${MIN_NODES_SIZE:-3}"
  echo "swarm mode enabled: peers are behind $(dig +short $SERVICE_NAME) ip"
  while [[ $number_of_nodes -lt ${MIN_NODES_SIZE} ]]; do
    sleep 1
    SELF_IP=$(dig +short $(hostname))
    NODES=$(dig +short tasks.${SERVICE_NAME})
    number_of_nodes=$(( $(echo $NODES | grep -o '\s' | wc -l) + 1 )) >/dev/null
    echo "we found $number_of_nodes nodes"
    NODE_LIST=""
    for node in $NODES; do
      NODE_LIST="$NODE_LIST --join $node"
    done
  done
  cmd="rethinkdb --bind all $NODE_LIST"
  echo "running $cmd"
  exec $cmd
fi
